name: Push to Personal Repo for Vercel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Prepare output folder
        run: |
          rm -rf output
          mkdir output
          rsync -av --progress ./ output/ \
            --exclude .git \
            --exclude .github \
            --exclude node_modules

      - name: Push to personal repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_REPO_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: GraceKim527
          destination-repository-name: SKHUni-FE
          user-email: ${{ secrets.PERSONAL_EMAIL }}
          commit-message: '🔁 Sync from team repo: ${{ github.sha }}'
          target-branch: main
